import Link from 'next/link';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background py-20 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto prose dark:prose-invert">
                <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
                <p className="lead text-muted-foreground mb-8">Last updated: December 16, 2025</p>

                <div className="space-y-8">
                    <section>
                        <h2 className="text-2xl font-bold mb-4">1. Agreement to Terms</h2>
                        <p>
                            By accessing or using the Omini Listen website, application, or services (collectively, the "Service"), provided by Omini ("we," "us," or "our"),
                            you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">2. Description of Service</h2>
                        <p>
                            Omini Listen is an AI-powered personal assistant that records, transcribes, and analyzes audio conversations to provide summaries, action items,
                            and insights. The Service uses third-party Artificial Intelligence (AI) technologies to process your data.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">3. Recording Laws and Consent (IMPORTANT)</h2>
                        <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg border border-yellow-200 dark:border-yellow-800">
                            <p className="font-semibold text-yellow-800 dark:text-yellow-200">
                                You are solely responsible for complying with all applicable laws regarding the recording of conversations.
                            </p>
                            <p className="mt-2 text-sm">
                                Many jurisdictions require the consent of all parties to a conversation before it can be recorded ("Two-Party Consent" laws).
                                By using the Service, you represent and warrant that you will obtain all necessary consents from meeting participants
                                before recording. Omini Listen disclaims all liability for your failure to comply with these laws.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">4. User Content and Data Ownership</h2>
                        <p>
                            <strong>Your Data:</strong> You retain full ownership of all audio recordings, transcripts, summaries, and other content you upload or
                            generate via the Service ("User Content").
                        </p>
                        <p className="mt-2">
                            <strong>License to Us:</strong> By using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce,
                            and process your User Content solely for the purpose of providing and improving the Service for you. We do not sell your
                            personal conversation data to third parties for advertising purposes.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">5. Accuracy of AI Outputs</h2>
                        <p>
                            The Service utilizes generative AI, which may occasionally produce incorrect, misleading, or "hallucinated" information.
                            Transcripts and summaries may not be 100% accurate. You acknowledge that you should verify the accuracy of any critical
                            information generated by the Service before relying on it or taking action based upon it. We govern no warranty regarding
                            the accuracy of the AI analysis.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">6. Acceptable Use</h2>
                        <p>You agree not to use the Service to:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-1">
                            <li>Record conversations in violation of applicable privacy or wiretapping laws.</li>
                            <li>Process sensitive personal data (e.g., health information, financial data) without appropriate safeguards.</li>
                            <li>Reverse engineer, decompile, or attempt to extract the source code of the Service.</li>
                            <li>Use the Service for any illegal, harmful, or abusive purpose.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">7. Privacy Policy</h2>
                        <p>
                            Your use of the Service is also governed by our <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>,
                            which describes how we collect, use, and share your information.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">8. Limitation of Liability</h2>
                        <p>
                            To the maximum extent permitted by law, Omini shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
                            including without limitation, loss of profits, data, use, or goodwill, resulting from (i) your access to or use of the Service;
                            (ii) any conduct or content of any third party on the Service; or (iii) unauthorized access, use, or alteration of your transmissions or content.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">9. Termination</h2>
                        <p>
                            We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that we believe violates
                            these Terms or is harmful to other users of the Service, us, or third parties, or for any other reason.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">10. Contact Information</h2>
                        <p>
                            If you have any questions about these Terms, please contact us at: <a href="mailto:legal@esap.ai" className="text-blue-600 hover:underline">legal@esap.ai</a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
