export const SYSTEM_PRESETS = [
    {
        id: -1,
        name: 'HR Manager',
        config: {
            role: 'HR Manager',
            output_fields: {
                transcript: true,
                summary_english: true,
                summary_arabic: false,
                action_items: true,
                deadlines: true,
                calendar_sync: true,
                budget_notes: false,
                decisions: true,
                general_notes: true,
            },
            user_input: '',
            custom_field_only: false,
        },
        is_default: false,
        is_system: true,
    },
    {
        id: -2,
        name: 'Sales Manager',
        config: {
            role: 'Sales Manager',
            output_fields: {
                transcript: true,
                summary_english: true,
                summary_arabic: false,
                action_items: true,
                deadlines: true,
                calendar_sync: true,
                budget_notes: true,
                decisions: true,
                general_notes: false,
            },
            user_input: '',
            custom_field_only: false,
        },
        is_default: false,
        is_system: true,
    },
    {
        id: -3,
        name: 'Project Manager',
        config: {
            role: 'Project Manager',
            output_fields: {
                transcript: true,
                summary_english: true,
                summary_arabic: false,
                action_items: true,
                deadlines: true,
                calendar_sync: true,
                budget_notes: true,
                decisions: true,
                general_notes: true,
            },
            user_input: '',
            custom_field_only: false,
        },
        is_default: false,
        is_system: true,
    },
    {
        id: -4,
        name: 'Executive',
        config: {
            role: 'Executive',
            output_fields: {
                transcript: false,
                summary_english: true,
                summary_arabic: false,
                action_items: true,
                deadlines: true,
                calendar_sync: false,
                budget_notes: true,
                decisions: true,
                general_notes: false,
            },
            user_input: '',
            custom_field_only: false,
        },
        is_default: false,
        is_system: true,
    },
    {
        id: -5,
        name: 'Custom',
        config: {
            role: 'Custom',
            output_fields: {
                transcript: true,
                summary_english: true,
                summary_arabic: true,
                action_items: true,
                deadlines: true,
                calendar_sync: true,
                budget_notes: true,
                decisions: true,
                general_notes: true,
            },
            user_input: '',
            custom_field_only: false,
        },
        is_default: false,
        is_system: true,
    },
];
